### PR TITLE
Add optional support for embedded-hal alpha

### PR DESCRIPTION
**Pull request by hannobraun**

### CODE REVIEW

**Comment by hannobraun** [comment]
Same as my other pull request: CI fails on nightly (for docs only), but that seems unrelated to this pull request.

**Comment by hannobraun** [comment]
I just discovered that this didn't build, if both the `embedded-hal-alpha` and `table-decoder` features were enabled. I added the required change to the existing commit.

**Comment by leshow** [comment]
They just changed the name of the method? Is that the only change?

**Comment by hannobraun** [comment]
Force-pushed the commit to solve the merge conflict.

> They just changed the name of the method? Is that the only change?

As far as `InputPin` is concerned, yes, this is the only change, as far as I know.

**Comment by leshow** [comment]
Thanks for your PRs, this has been published as 0.3.0 on crates.io

**Comment by hannobraun** [comment]
> Thanks for your PRs, this has been published as 0.3.0 on crates.io

Thank you!

**Pull request merged**
